product_File=open(r"C:\Users\HP\Desktop\AIML\PythonLearning\InventoryManagement.txt","a+")
id=input("enther Id")
name=input("enter product name")
price=input("enter profuct price")
quantity=input("enter Quantity")
category=input("enter category")
product_File.writelines([id,",",name,",",price,",",quantity,",",category,"\n"])
product_File.seek(0)
a=product_File.read()
print(a)
product_File.close()